title: Heng Ee # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. Candidate @ Monash University Malaysia. 
  <br>
  Research in the adoption and application of machine learning in mental health.
  <br>
  I'm also a mobile developer, YouTube content creator and start-up founder in the dream.
  <br>
  <a href="https://www.linkedin.com/in/d3aries/">LinkedIn Profile</a> 
  <br>
  <a href="https://stackoverflow.com/users/story/10191554?view=Timeline">StackOverflow Profile</a>   
  <script src="https://apis.google.com/js/platform.js"></script>
  <div class="g-ytsubscribe" data-channelid="UCe_QLqna7cFtTCfZ0a8pycg" data-layout="full" data-count="default"></div>
  
theme: jekyll-theme-minimal
google_analytics: UA-169263630-1 # your Google Analytics tracking ID here
